trigger:
  branches:
    include:
      - main
 
pool:
  name: bela-beka-agent # Use the name of your agent pool

variables:
  azureServiceConnection: 'beka-bela-coonectioAR'
  resourceGroupName: 'Bereketab'
  location: 'Poland Central'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: ps  # PowerShell script type
      scriptLocation: inlineScript
      inlineScript: |
        # Check if Azure CLI is installed, and if not, install it
        if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
          Write-Host "Azure CLI not found. Installing Azure CLI..."
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile install-azure-cli.ps1
          .\install-azure-cli.ps1
        } else {
          Write-Host "Azure CLI is already installed."
        }
        
        # Run Azure CLI commands
        az bicep install
        az deployment group create `
          --resource-group $(resourceGroupName) `
          --template-file iac/main.bicep `
          --parameters @iac/parameters/dev.parameters.json
