trigger:
  branches:
    include:
      - main
 
pool:
 
  name: bela-beka-agent # Use the name of your agent pool

 
variables:
  azureServiceConnection: 'beka-bela-coonectioAR'
  resourceGroupName: 'Bereketab'
  location: 'Poland Central'
 
steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az bicep install
        az deployment group create \
          --resource-group $(resourceGroupName) \
          --template-file iac/main.bicep \
          --parameters @iac/parameters/dev.parameters.json
        